### ISSUE TITLE
NameError: name 'pout' is not defined

### ISSUE THREAD

**Issue by kraftydevil** [Jaymon/transcribe#3]
```
$ transcribe speech test.wav
[I] Converting test.wav to ogg at /var/folders/tl/hrcdxt0s2ts9nb99kjmz11zc0000gn/T/test.ogg
[I] Uploading /var/folders/tl/hrcdxt0s2ts9nb99kjmz11zc0000gn/T/test.ogg to Google cloud storage bucket obfuscated-obfuscated-123456
[I] Google cloud storage uri gs://obfuscated-obfuscated-123456/test.ogg
[I] Beginning transcription
[I] Transcription finished in 0:00:04
[I] Deleting file from Google cloud storage gs://obfuscated-obfuscated-123456/test.ogg
Traceback (most recent call last):
  File "/usr/local/bin/transcribe", line 10, in <module>
    sys.exit(console())
  File "/usr/local/lib/python3.7/site-packages/transcribe/__main__.py", line 70, in console
    exit(__name__)
  File "/usr/local/lib/python3.7/site-packages/captain/__init__.py", line 41, in exit
    ret_code = s.run(raw_args)
  File "/usr/local/lib/python3.7/site-packages/captain/__init__.py", line 176, in run
    ret_code = callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/transcribe/__main__.py", line 64, in main_speech
    pout.v(time)
NameError: name 'pout' is not defined
```
Looks like most of the call to speech is working. I'm a python novice so I don't know if `pout` is a typo or something that wasn't imported.

**Comment by Jaymon** [comment]
Bah! Sorry about that, I left in some debugging code, pout is [this module](https://github.com/Jaymon/pout) which I use to debug stuff and is globally available in my environment. I've removed the references and updated to 0.0.7.

Thanks again :)
